export type ProjectCategory =
  | "featured"
  | "ai-powered"
  | "web3"
  | "business"
  | "productivity"
  | "education"
  | "web-app";

export interface Project {
  slug: string;
  title: string;
  description: string;
  categories: ProjectCategory[];
  badges: {
    label: string;
    variant: "featured" | "ai" | "web3" | "business" | "web-app" | "education" | "productivity" | "info";
  }[];
  featured?: boolean;
  techTags: string[];
  aiTools?: string[];
  features: string[];
  link: { label: string; href: string };
  deploymentBadge: string;
  impactRating?: { stars: number; label: string };
}

export const projects: Project[] = [
  {
    slug: "mirror-the-audiobook",
    title: "Mirror: The Audiobook — Neural Text-to-Speech Production",
    description:
      "A professional-grade, commercially-distributed audiobook production of my published novel, Mirror. Combines Amazon Polly's Neural Text-to-Speech engine with hand-tuned SSML markup — controlling pacing, emphasis, and pauses — to produce natural, lifelike narration suitable for commercial release. Rendered audio is processed and stored through a Python and AWS S3 pipeline, then published to the Google Play Store audiobook catalog.",
    categories: ["ai-powered", "business", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Audiobook", variant: "business" },
      { label: "AWS Polly", variant: "info" },
    ],
    featured: true,
    techTags: ["Amazon Polly (Neural Engine)", "SSML", "Python", "AWS S3", "Google Play Console"],
    aiTools: ["Amazon Polly Neural TTS"],
    features: [
      "Neural Text-to-Speech Narration",
      "Custom SSML Prosody Control",
      "Commercial-Grade Audio Mastering",
      "S3-Backed Rendering Pipeline",
      "Google Play Store Distribution",
    ],
    link: { label: "Listen on Google Play", href: "https://play.google.com/store/audiobooks/details/Robin_Pandey_Mirror?id=AQAAAEAq1luWYM" },
    deploymentBadge: "AWS Polly Neural · Live on Google Play",
    impactRating: { stars: 5, label: "Creative & Commercial Impact" },
  },
  {
    slug: "deep-agent-ai",
    title: "Deep Agent AI: Enterprise Human-in-the-Loop Orchestrator",
    description:
      "An enterprise operations \"deep agent\" built on the supervisor-style deepagents harness (LangGraph runtime) and served as a streaming FastAPI service. Given a natural-language request, it plans with todo tools, delegates focused data-gathering to a dedicated research subagent so raw records never flood the orchestrator's context, drafts analysis in a sandboxed filesystem workspace, and only submits a change request to a downstream enterprise system after a human approves, edits, or rejects it at a LangGraph interrupt. Models are served through Amazon Bedrock with IAM-based auth via the ECS task role, and the agent is grounded against fabrication — it must fetch real records rather than invent them, degrading gracefully to a clearly labeled \"not configured\" state when no backend is wired in.",
    categories: ["ai-powered", "business", "web-app", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Agentic Orchestration", variant: "business" },
      { label: "AWS Bedrock", variant: "info" },
    ],
    featured: true,
    techTags: ["FastAPI", "LangGraph", "deepagents", "Amazon Bedrock (Claude)", "Server-Sent Events", "SQLite / Postgres", "Docker", "ECS Fargate"],
    aiTools: ["Claude Opus 4.8 (Bedrock)", "Claude Sonnet 5 (Bedrock)", "Agentic Workflows", "Human-in-the-Loop Approval"],
    features: [
      "Supervisor-Style Deep Agent",
      "Research Subagent Delegation",
      "Human-in-the-Loop Approval Gates",
      "SSE Streaming API",
      "Sandboxed Filesystem Workspace",
      "Grounded Tool Calling (No Fabrication)",
      "ECS Fargate Deployment",
    ],
    link: { label: "Request Demo", href: "#contact" },
    deploymentBadge: "Docker · ECS-Ready",
    impactRating: { stars: 5, label: "Enterprise Agent Impact" },
  },
  {
    slug: "obsvagent-observability-layer",
    title: "Obsvagent: Shared Observability, RAG-Checker & Compliance-Audit Layer",
    description:
      "A single installable Python package that centralizes telemetry, RAG citation-checking, and compliance auditing across a multi-repo AI ecosystem (RiskGuard AI, Deep Agent AI, Stablecoin Treasury Orchestrator) instead of each service re-implementing it. Telemetry is captured at exactly three seams — the FastAPI edge, a wrapped multi-LLM gateway (Claude/Gemini/DeepSeek), and LangGraph node transitions — as OpenTelemetry spans with GenAI semantic conventions, keyed by time-sortable ULID trace IDs and merged into graph state through a dedicated reducer. Expensive work (citation verification, drift detection, hash-chaining, alert evaluation) runs off the hot path in an async Checker service, following a fail-open-for-telemetry, fail-closed-for-compliance design so a broken observability layer never breaks a user request but a broken audit trail always halts one.",
    categories: ["ai-powered", "business", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Observability", variant: "business" },
      { label: "OpenTelemetry", variant: "info" },
    ],
    featured: true,
    techTags: ["Python", "OpenTelemetry", "FastAPI", "LangGraph", "Neon Postgres", "ULID", "Docker"],
    aiTools: ["Claude", "Gemini", "DeepSeek", "RAG Citation Checking"],
    features: [
      "OTel-Native Telemetry Schema",
      "ULID Time-Sortable Trace IDs",
      "LangGraph Telemetry Reducer",
      "RAG Citation Checker",
      "Hash-Chained Audit Trail",
      "Alert Taxonomy & Thresholds",
      "Shared Cross-Repo Package",
    ],
    link: { label: "Request Demo", href: "#contact" },
    deploymentBadge: "Python Package · Contracts Frozen",
    impactRating: { stars: 5, label: "Reliability Engineering Impact" },
  },
  {
    slug: "stablecoin-treasury-orchestrator",
    title: "Stablecoin Treasury Orchestrator: Settlement & Compliance Engine",
    description:
      "A fiat ⇄ stablecoin settlement orchestrator with a SHA-256 hash-chained, tamper-evident audit trail and a maker-checker compliance workflow — architected to be \"exam-ready\" for bank-style SOX/AML regulatory review. A mock AML agent scores every transaction against jurisdiction, size, velocity, and structuring heuristics, routing anything risky into a reviewer queue before it can settle. Demo/portfolio project only: no real bank, blockchain, or funds are involved — every transaction, entity, and AML rule is simulated to demonstrate the architecture and controls, not to move real money.",
    categories: ["web3", "business", "web-app", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Web3/Stablecoin", variant: "web3" },
      { label: "Compliance/AML", variant: "business" },
      { label: "Demo Only", variant: "info" },
    ],
    featured: true,
    techTags: ["Next.js 15", "TypeScript", "Tailwind CSS v4", "Upstash Redis", "Docker", "SHA-256 Hash Chain"],
    aiTools: ["Claude Sonnet 5"],
    features: [
      "Hash-Chained Audit Trail",
      "Maker-Checker Exception Queue",
      "Mock AML Risk Scoring",
      "CSV / PDF Auditor Export",
      "Dual Storage Backends (File + Redis)",
      "Real-Time Settlement State Machine",
    ],
    link: { label: "Live Demo", href: "https://stablecoin-orchestrator-alpha.vercel.app" },
    deploymentBadge: "Demo · Vercel + Redis",
  },
  {
    slug: "riskguard-ai",
    title: "RiskGuard AI: Enterprise Risk Analytics & Automated Remediation",
    description:
      "An enterprise risk analytics platform that scores loan customers for default risk with a trained XGBoost pipeline (0.90 ROC-AUC), and for high-risk customers, kicks off a stateful LangGraph agent that retrieves applicable policy documents (parent-child RAG), drafts a remediation plan via Claude on Amazon Bedrock, runs it through a deterministic compliance check, and pauses for human compliance-officer sign-off before finalizing. The same workflow is also exposed as an MCP server, so any MCP-speaking AI client (Claude Desktop, Cursor, etc.) can call it directly. Live and fully functional on AWS ECS Fargate — real XGBoost scoring, real Postgres persistence, and real Bedrock/Claude agent calls; built as a portfolio demonstration using synthetic loan data, not real customer records.",
    categories: ["ai-powered", "business", "web-app", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Fintech", variant: "business" },
      { label: "AWS Cloud", variant: "info" },
    ],
    featured: true,
    techTags: ["FastAPI", "XGBoost", "LangGraph", "Amazon Bedrock (Claude)", "MCP", "SQLAlchemy 2.0", "Neon Postgres", "Docker"],
    aiTools: ["Claude Sonnet 5 (Bedrock)", "Agentic Workflows", "RAG Retrieval", "MCP Tool Calling"],
    features: [
      "XGBoost Risk Scoring (0.90 ROC-AUC)",
      "Stateful LangGraph Agent",
      "Parent-Child RAG Retrieval",
      "Human-in-the-Loop Approval",
      "Automated Compliance Checks",
      "Full Audit Trail Logging",
      "MCP Server (Claude/Cursor Tools)",
    ],
    link: { label: "Live API (Swagger)", href: "http://riskguard-alb-143265901.us-east-1.elb.amazonaws.com/docs" },
    deploymentBadge: "AWS ECS Fargate",
    impactRating: { stars: 5, label: "Risk & Compliance Impact" },
  },
  {
    slug: "mastering-ai-agentic-loops",
    title: "Mastering AI Agentic Loops: Engineering-First Course Platform",
    description:
      "A hands-on, engineering-first course platform for building reliable, stateful, autonomous AI agents. Learners progress from raw ReAct cycles to reflection, planning, and multi-agent swarms across five self-contained modules — each pairing core theory with production-grade Python boilerplate and a hands-on project.",
    categories: ["web-app", "education", "ai-powered", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Education", variant: "education" },
      { label: "Web App", variant: "web-app" },
    ],
    featured: true,
    techTags: ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS 4", "Prisma ORM", "Framer Motion"],
    aiTools: ["Reflection & Self-Correction", "Tool Use & Planning", "Multi-Agent Orchestration"],
    features: [
      "Live ReAct Loop Animation",
      "5-Module Engineering Curriculum",
      "Simulated Agent Execution Terminal",
      "Interactive Quizzes & Code Blocks",
      "Persistent Progress Tracking (Prisma)",
      "Certification Exam & Printable Certificate",
    ],
    link: { label: "Live Production", href: "https://ai-agentic-loop.vercel.app/" },
    deploymentBadge: "Next.js 16 · Turbopack",
    impactRating: { stars: 5, label: "AI Education Impact" },
  },
  {
    slug: "open-claw",
    title: "Open Claw: Autonomous Lead-Search Agentic System",
    description:
      "A self-built agentic system that autonomously hunts and qualifies sales leads end-to-end. Open Claw orchestrates a fleet of sub-agents that crawl the web, extract company and contact signals, enrich them against intent criteria, and surface a ranked, deduplicated lead list — turning hours of manual prospecting into a single autonomous run.",
    categories: ["web-app", "ai-powered", "featured", "business"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Lead Generation", variant: "business" },
      { label: "Agentic System", variant: "web-app" },
    ],
    featured: true,
    techTags: ["Python", "Multi-Agent Orchestration", "Tool Calling", "Web Scraping", "Structured Extraction", "LLM Integration"],
    aiTools: ["Claude", "Agentic Workflows", "Autonomous Sub-Agents"],
    features: [
      "Autonomous Lead Discovery",
      "Multi-Agent Orchestration",
      "Contact & Signal Enrichment",
      "Intent-Based Qualification",
      "Ranked & Deduplicated Output",
      "Human-in-the-Loop Review",
    ],
    link: { label: "Request Demo", href: "#contact" },
    deploymentBadge: "Self-Built Agentic System",
    impactRating: { stars: 5, label: "Sales & GTM Impact" },
  },
  {
    slug: "apollo-18-token-platform",
    title: "Apollo 18 Token Platform",
    description:
      "Complete Web3 application with multi-wallet connectivity, developed using ChatGPT, Gemini, and Claude. Features WalletConnect integration, React Native PWA, and serverless Google Apps Script backend.",
    categories: ["web3", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Web3/Blockchain", variant: "web3" },
      { label: "Multi-LLM Built", variant: "ai" },
    ],
    featured: true,
    techTags: ["React Native", "Web3", "Ethereum", "LLM-Generated", "Google Apps Script"],
    aiTools: ["ChatGPT", "Gemini", "Claude"],
    features: [
      "WalletConnect v2 Integration",
      "Multi-Network Support",
      "Gasless Transaction Logic",
      "Real-time Token Tracking",
      "Secure Smart Contract Ops",
      "PWA Offline Capabilities",
    ],
    link: { label: "Live Demo", href: "https://apollo18token.com" },
    deploymentBadge: "Production",
  },
  {
    slug: "todo-application",
    title: "To-Do Application",
    description:
      "Modern task management application with drag & drop, categories, and local storage. Built with React and deployed on Vercel using AI-assisted development.",
    categories: ["productivity"],
    badges: [
      { label: "Productivity", variant: "productivity" },
      { label: "Modern Stack", variant: "info" },
    ],
    techTags: ["React", "Local Storage", "Drag & Drop", "Vercel"],
    features: [
      "Drag & Drop Sort",
      "Local Persistence",
      "Dark/Light Mode",
      "Category Filtering",
      "Smart Due Dates",
      "Priority Tagging",
    ],
    link: { label: "Live Demo", href: "https://todo-app-indol-seven-99.vercel.app" },
    deploymentBadge: "Vercel",
  },
  {
    slug: "insuragent-ai-corpus",
    title: "InsurAgent AI \"Corpus\": Policy-Aware Coverage Intelligence",
    description:
      "An intelligent insurance analysis system that transforms complex carrier PDF documents into queryable knowledge graphs with real-time source citations and deterministic quote generation. Built on a production-grade RAG architecture with ChromaDB persistence and FastAPI serving. When an agent uploads a policy PDF, the system parses tables and clauses via PyMuPDF, applies a Parent-Child chunking strategy with Cross-Encoder re-ranking to surface the most relevant coverage sections, and routes queries through a LangGraph agent that decides between semantic policy search and Python-calculated quotes — all rendered through a Liquid Glass HUD dashboard with live citation tracing back to the exact page and paragraph.",
    categories: ["web-app", "ai-powered", "featured", "business"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Insurance", variant: "business" },
      { label: "Web App", variant: "web-app" },
    ],
    featured: true,
    techTags: ["FastAPI", "ChromaDB", "LangGraph", "React", "Docker", "Groq LLM", "PyMuPDF", "Tailwind CSS"],
    features: [
      "Parent-Child Retrieval",
      "Cross-Encoder Re-Ranking",
      "Agentic Tool Routing",
      "Source Citations",
      "Quote Calculation Engine",
      "RAGAS Evaluation",
      "PDF Table Extraction",
      "Vector Similarity Search",
    ],
    link: { label: "Live Production", href: "https://rag-llm-demo.vercel.app/" },
    deploymentBadge: "Vercel + Render | Free Tier",
    impactRating: { stars: 5, label: "Insurance & LegalTech" },
  },
  {
    slug: "deepfocus-ai-genesis",
    title: "DeepFocus AI \"Genesis\": Neural-Focused Work Intelligence",
    description:
      "An intelligent focus optimization system that transforms scattered work sessions into structured cognitive sprints with real-time hurdle detection and digital twin visualization. Built on a scalable architecture with PostgreSQL persistence and FastAPI serving. When a user initiates a focus session, the system captures sprint data, applies LLM-generated puzzle logic to detect cognitive obstacles, and maps performance metrics to a 3D \"biological brain\" model — all orchestrated through a defined implementation pipeline from schema design to final technical walkthrough.",
    categories: ["web-app", "productivity", "ai-powered", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Productivity", variant: "productivity" },
      { label: "Web App", variant: "web-app" },
    ],
    featured: true,
    techTags: ["FastAPI", "PostgreSQL", "3D Digital Twin", "WebSockets", "Docker", "GitHub", "LLM Integration", "Edge Layer Processing"],
    features: [
      "Focus Session Tracking",
      "Cognitive Load Analytics",
      "Hurdle Detection Logic",
      "Neural Map Visualization",
      "Sprint Validation",
    ],
    link: { label: "Live Production", href: "https://attention-builder.vercel.app/" },
    deploymentBadge: "Local + Cloud | $",
    impactRating: { stars: 5, label: "Productivity Impact" },
  },
  {
    slug: "apollos-agentic-ai-interactive-learning-academy",
    title: "Apollo's Agentic AI: Interactive Learning Academy",
    description:
      "A comprehensive digital learning platform designed for developers, product managers, and decision-makers to master orchestrating intelligent agent behaviors. The platform features an interactive curriculum, a dynamic \"live sandbox\" UI, secure progress tracking, and an automated final exam credentialing system.",
    categories: ["web-app", "education", "ai-powered", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Education", variant: "education" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Web App", variant: "web-app" },
    ],
    featured: true,
    techTags: ["Next.js 15", "Clerk Auth (v7)", "Tailwind CSS", "Prisma ORM", "PostgreSQL", "Framer Motion", "React Spring", "TypeScript"],
    aiTools: ["Agentic Workflows", "RAG Concepts", "Multi-Agent Orchestration"],
    features: [
      "Secure Clerk Authentication",
      "Persistent Progress Tracking",
      "Automated Certification Exams",
      "Dynamic Terminal Sandbox UI",
    ],
    link: { label: "Live Production", href: "https://agentic-ai-course-umber.vercel.app/" },
    deploymentBadge: "Next.js App Router",
    impactRating: { stars: 5, label: "Platform Grade" },
  },
  {
    slug: "apollo-enrollment-engine",
    title: "Apollo Enrollment Engine: AI-Powered Music School Automation",
    description:
      "A fully automated enrollment pipeline for Apollo Performing Arts & Academy that converts trial lesson bookings into personalized Gmail drafts with zero manual data entry. Built entirely on free tools with no monthly SaaS fees. When a Calendly booking arrives, the system extracts parent and student information using the Groq AI API, builds a personalized enrollment email from a dynamic template, and creates a ready-to-send Gmail draft — all triggered from a password-protected web dashboard accessible from any device.",
    categories: ["ai-powered", "education", "web-app", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Education", variant: "education" },
      { label: "Web App", variant: "web-app" },
    ],
    featured: true,
    techTags: ["Python", "Flask", "Groq AI", "Gmail API", "Google OAuth", "PythonAnywhere", "GitHub", "Calendly"],
    features: [
      "AI Email Extraction",
      "Gmail Draft Automation",
      "Mobile-Friendly Dashboard",
      "Calendly Integration",
      "Walk-in & Phone Booking Support",
      "Booking History Log",
    ],
    link: { label: "Live Dashboard", href: "https://robinpandey.pythonanywhere.com/admin" },
    deploymentBadge: "Local + Cloud | $0/mo",
    impactRating: { stars: 5, label: "Operational Impact" },
  },
  {
    slug: "apollo-tax",
    title: "Apollo Tax: The Privacy-First Business Command Center",
    description:
      "A CPA-grade multi-entity orchestrator for S-Corps and LLCs that prioritizes data sovereignty. By utilizing a local-first Docker architecture, the platform ensures sensitive corporate financials, EINs, and shareholder PII never touch the cloud—keeping your data strictly on your company PC.",
    categories: ["ai-powered", "web-app", "featured", "business"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Privacy-First", variant: "ai" },
      { label: "CPA-Grade", variant: "business" },
      { label: "Local Docker", variant: "info" },
    ],
    featured: true,
    techTags: ["Next.js 15", "FastAPI", "Docker Compose", "Tailwind CSS", "Pydantic", "pdfrw", "JSON Persistence"],
    aiTools: ["Claude 3.5 Sonnet", "Gemini 3.1 Pro", "Agentic Workflows"],
    features: [
      "Local Docker Node",
      "OBBBA 2025 Logic",
      "6-Shareholder Matrix",
      "Audit-Shield Guardrails",
      "Decoupled Showcase",
      "Non-Root Security",
    ],
    link: { label: "Live Production", href: "https://frontend-apollo-tech1.vercel.app/" },
    deploymentBadge: "Docker Local",
    impactRating: { stars: 5, label: "Privacy Grade" },
  },
  {
    slug: "shadow-trader",
    title: "Shadow Trader: AI-Driven Quant Intelligence",
    description:
      "An end-to-end Medallion data pipeline (Bronze/Silver/Gold) that automates Bitcoin trend-following strategies. The app identifies 🟢 BULLISH and 🔴 BEARISH signals by processing 15+ years of market data through an automated AWS Lambda and S3 ecosystem.",
    categories: ["ai-powered", "web-app", "featured", "business"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Fintech", variant: "business" },
      { label: "AWS Cloud", variant: "info" },
    ],
    featured: true,
    techTags: ["Python", "AWS S3", "Streamlit", "Boto3", "Pandas", "Plotly", "AlphaVantage API"],
    aiTools: ["Claude 4.6", "Gemini 3.1 Pro", "GPT-OSS 120B", "Agentic Workflows"],
    features: [
      "Live Coinbase Integration",
      "Dynamic SMA Lab",
      "Fully Serverless Architecture",
      "Multi-LLM Strategy",
    ],
    link: { label: "Live Production", href: "https://www.apollotechnologiesus.com/quant-trading" },
    deploymentBadge: "Serverless",
    impactRating: { stars: 5, label: "Quant Impact" },
  },
  {
    slug: "digital-twin-stable-edition",
    title: "Digital Twin (Stable Edition)",
    description:
      "A high-fidelity 3D Digital Twin application optimized for Maximum Stability and Performance. This version ensures reliable rendering across all hardware and browsers using industry-standard stable shaders and a direct rendering pipeline.",
    categories: ["ai-powered", "web-app", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI-Augmented", variant: "ai" },
      { label: "3D Digital Twin", variant: "web-app" },
      { label: "High-Stability", variant: "business" },
    ],
    featured: true,
    techTags: ["Three.js", "React", "Node.js", "Vite", "Standard Shaders", "Glassmorphism"],
    aiTools: ["Antigravity AI", "Claude Sonnet", "ChatGPT-o1"],
    features: [
      "Maximum Stability Architecture",
      "High-End Glassmorphism UI",
      "Cinematic Ambient Lighting",
      "Neural Core Anatomy Visualization",
      "Auto-Rotation & Manual Orbit",
      "Optimized for Mobile & Legacy GPUs",
    ],
    link: { label: "Live Production", href: "https://digital-twin-human-body-b06l6p9xz-apollo-tech1.vercel.app" },
    deploymentBadge: "Verified Fix",
    impactRating: { stars: 5, label: "Stability Grade" },
  },
  {
    slug: "latent-job-board",
    title: "Latent Job Board",
    description:
      "A modern, full-stack job marketplace connecting employers with talent. Built on the cutting-edge Next.js 16 with Turbopack, featuring role-based dashboards, secure NextAuth authentication, and a robust PostgreSQL database managed via Prisma.",
    categories: ["web-app", "business", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Job Market", variant: "web-app" },
      { label: "Next.js 16", variant: "ai" },
      { label: "Prisma", variant: "business" },
    ],
    featured: true,
    techTags: ["Next.js 16", "Prisma ORM", "PostgreSQL", "NextAuth", "Tailwind CSS", "Turbopack"],
    aiTools: ["ChatGPT", "Claude Sonnet", "Gemini 2.0"],
    features: [
      "Employer & Candidate Dashboards",
      "Real-time Application Tracking",
      "Saved Jobs & Alerts",
      "Server-Side Rendering (SSR)",
    ],
    link: { label: "Live Demo", href: "https://latent-job-board.vercel.app/" },
    deploymentBadge: "Production",
  },
  {
    slug: "apollo-technologies-prompt-engineering-platform",
    title: "Apollo Technologies - Prompt Engineering Platform",
    description:
      "Professional AI training platform for mastering prompt engineering. Features comprehensive courses on AI communication fundamentals, agentic workflows, and RAG pipelines. Includes interactive AI prompt sandbox with real-time heuristic scoring engine.",
    categories: ["education", "ai-powered", "business", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Education", variant: "education" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Training Platform", variant: "business" },
    ],
    featured: true,
    techTags: ["React", "Node.js", "AI Integration", "LMS", "Interactive Tools", "Heuristic Engine"],
    aiTools: ["ChatGPT", "Claude", "Gemini"],
    features: [
      "AI Communication Fundamentals",
      "Agentic Workflows & RAG",
      "Interactive Prompt Sandbox",
      "Real-time Scoring Engine",
      "500+ Active Students",
      "4.9/5 Rating",
    ],
    link: { label: "Live Demo", href: "https://prompt-engineering-courses.vercel.app" },
    deploymentBadge: "Production",
    impactRating: { stars: 5, label: "Learning Impact" },
  },
  {
    slug: "buildfolio-platform",
    title: "BuildFolio Platform",
    description:
      "Portfolio-building platform for developers to create deployable projects that impress hiring managers. Features interactive browser IDE, one-click deployment, resume builder integration, and GitHub authentication. This is a full-stack development.",
    categories: ["web-app", "business", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Web Application", variant: "web-app" },
      { label: "AI-Assisted", variant: "ai" },
      { label: "Business Platform", variant: "business" },
    ],
    featured: true,
    techTags: ["React", "Node.js", "TypeScript", "Tailwind CSS", "Next.js", "Chart.js", "Prisma", "Stripe", "LLM-Assisted"],
    aiTools: ["ChatGPT", "Gemini", "Claude"],
    features: [
      "Interactive Browser IDE",
      "One-Click Deployment",
      "Resume Builder Integration",
      "GitHub Integration",
      "Project Catalog",
      "Difficulty Levels",
    ],
    link: { label: "Live Demo", href: "https://buildfolio.tech" },
    deploymentBadge: "Production",
    impactRating: { stars: 5, label: "Hiring Impact" },
  },
  {
    slug: "apollo-audiobook-converter",
    title: "Apollo Audiobook Converter",
    description:
      "Full-stack web application that converts PDF documents to high-quality audiobooks using Amazon Polly. Features secure file handling, drag-and-drop UI, and professional audio output.",
    categories: ["productivity"],
    badges: [
      { label: "Cloud App", variant: "info" },
      { label: "Flask/Python", variant: "info" },
      { label: "AWS Polly", variant: "info" },
    ],
    techTags: ["Python", "Flask", "AWS Polly", "JavaScript", "PythonAnywhere"],
    features: [
      "AWS Neural Engine",
      "Smart PDF Extraction",
      "Batch Processing",
      "Secure Temp Storage",
      "High-Fidelity MP3",
      "Cloud Deployment",
    ],
    link: { label: "Live Demo", href: "" },
    deploymentBadge: "PythonAnywhere",
  },
  {
    slug: "ai-resume-optimizer",
    title: "AI Resume Optimizer",
    description:
      "Intelligent resume analysis tool with ATS optimization algorithms designed to maximize interview callback rates. Features real-time match scoring against job descriptions, semantic keyword detection, and actionable optimization recommendations. Built as a scalable full-stack serverless application with a robust Python backend.",
    categories: ["ai-powered", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Career Tools", variant: "info" },
      { label: "AI-Powered", variant: "ai" },
      { label: "Serverless", variant: "info" },
    ],
    featured: true,
    techTags: ["Python", "HTML5/CSS3", "JavaScript", "Vercel", "Serverless"],
    aiTools: ["ChatGPT", "Claude", "Gemini"],
    features: [
      "Semantic Keyword Match",
      "Real-Time ATS Scoring",
      "Gap Analysis Engine",
      "Format Auto-Validation",
      "Action Verb Suggestions",
      "PDF & Docx Parsing",
    ],
    link: { label: "Live Demo", href: "https://resume-optimizer-one-tau.vercel.app/" },
    deploymentBadge: "Production · Vercel",
    impactRating: { stars: 5, label: "Career Impact" },
  },
  {
    slug: "aire-platform",
    title: "AIRE Platform",
    description:
      "A high-performance influencer engine for luxury resort bookings. Featuring an automated multi-tenancy edge proxy, dynamic subdomain routing, and AI-generated personalized itineraries.",
    categories: ["web-app", "business", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Multi-Tenant SaaS", variant: "web-app" },
      { label: "Gemini 2.0", variant: "ai" },
      { label: "Fintech / Stripe", variant: "business" },
    ],
    featured: true,
    techTags: ["Next.js 16", "TypeScript", "Drizzle ORM", "Postgres (Neon)", "Turbopack", "Stripe Connect", "Cloudinary", "Gemini 2.0"],
    features: [
      "Structured JSON AI Output",
      "Dynamic Subdomain Rewriting",
      "Stripe Split Payments",
      "Edge Proxy Validation",
      "Automated Brand Theming",
      "Secure PII Isolation",
    ],
    link: { label: "View Audit", href: "https://aura-resorts.vercel.app/" },
    deploymentBadge: "Alpha 0.1.0",
    impactRating: { stars: 5, label: "Architecture Grade" },
  },
  {
    slug: "flowstate-deep-work-manager",
    title: "FlowState - Deep Work Manager",
    description:
      "Focus-driven task management application with nested task hierarchy, Pomodoro timer, and immersive focus mode. Features unlimited task nesting, 25-minute deep work sessions, command palette for quick actions, and keyboard-first navigation for maximum productivity.",
    categories: ["web-app", "productivity", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Web Application", variant: "web-app" },
      { label: "AI-Assisted", variant: "ai" },
      { label: "Productivity", variant: "productivity" },
    ],
    featured: true,
    techTags: ["React 19", "Next.js 15+", "TypeScript", "Lucide Icons", "LocalStorage", "CSS Animations", "LLM-Assisted"],
    aiTools: ["Claude Sonnet 4"],
    features: [
      "Nested Task Hierarchy",
      "25-Min Pomodoro Timer",
      "Focus Mode",
      "Command Palette (⌘K)",
      "Keyboard Shortcuts",
      "Auto-Save",
    ],
    link: { label: "Live Demo", href: "https://flowstate-gold.vercel.app/" },
    deploymentBadge: "Production",
    impactRating: { stars: 4, label: "Hiring Impact" },
  },
  {
    slug: "mirror-meditation-app",
    title: "Mirror Meditation App",
    description:
      "Cross-platform mobile meditation application built with React Native and Expo using AI-generated code. Features guided meditation, progress tracking, and responsive design.",
    categories: [],
    badges: [
      { label: "Mobile App", variant: "info" },
      { label: "AI-Assisted", variant: "ai" },
    ],
    techTags: ["React Native", "Expo", "Mobile", "LLM-Assisted"],
    aiTools: ["ChatGPT", "Gemini"],
    features: [
      "React Native / Expo Ark",
      "AI-Generated Audio Cues",
      "Biometric Auth Security",
      "Daily Progress Analytics",
      "Custom Meditation Flow",
      "Cross-Platform Deploy",
    ],
    link: { label: "Live Demo", href: "https://venerable-melomakarona-594663.netlify.app/" },
    deploymentBadge: "Netlify",
  },
  {
    slug: "linkstream-premium-url-shortener",
    title: "LinkStream - Premium URL Shortener",
    description:
      "Premium URL shortener featuring a modern glassmorphism UI, ambient animations, and secure link generation. Built with Flask and deployed on Vercel.",
    categories: ["web-app", "business", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Web Application", variant: "web-app" },
      { label: "AI-Assisted", variant: "ai" },
      { label: "Business Platform", variant: "business" },
    ],
    featured: true,
    techTags: ["Python", "Flask", "HTML5/CSS3", "Vercel", "Glassmorphism"],
    features: [
      "Custom URL Slugs",
      "Real-time Click Analytics",
      "Ambient Glassmorphism UI",
      "Secure Link Encryption",
      "Vercel Edge Deployment",
      "Automated SEO Meta",
    ],
    link: { label: "Live Demo", href: "https://ur-lshortner-two.vercel.app" },
    deploymentBadge: "Production",
  },
  {
    slug: "apollo-music-school-platform",
    title: "Apollo Music School Platform",
    description:
      "Advanced management platform for music academies featuring high-fidelity virtual classrooms. Built with Next.js 16 and React 19, it integrates Clerk multi-tenant auth, Drizzle ORM with Neon PostgreSQL, and automated faculty-student workflows.",
    categories: ["featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "EdTech", variant: "education" },
      { label: "Agentic Coding", variant: "ai" },
    ],
    featured: true,
    techTags: ["Next.js 16", "Clerk Auth", "Jitsi JaaS / Zoom SDK", "Drizzle/PostgreSQL", "Tailwind CSS v4"],
    aiTools: ["Antigravity AI", "ChatGPT-o1", "Gemini 2.0", "Claude 3.5"],
    features: [
      "Clerk Multi-Tenant Auth",
      "Jitsi JaaS Integration",
      "Drizzle RDS Orchestration",
      "Automated Billing Core",
      "Student Progress Portal",
      "Next.js 16 Edge Ready",
    ],
    link: { label: "Platform Access", href: "https://musicschool-platform.vercel.app/" },
    deploymentBadge: "Serverless Edge",
  },
  {
    slug: "apollo-soccer-academy",
    title: "Apollo Soccer Academy",
    description:
      "Sports academy website with AI-generated scheduling, registration systems, and team management. Part of 5-business website portfolio built with AI assistance.",
    categories: ["business"],
    badges: [
      { label: "Business", variant: "business" },
      { label: "AI-Generated", variant: "ai" },
    ],
    techTags: ["HTML5/CSS3", "JavaScript", "Forms", "AI-Generated"],
    features: [
      "Auto-Scheduling",
      "Team Management",
      "Parent Portal",
      "Player Stats Tracking",
      "Online Registration",
      "Automated Emails",
    ],
    link: { label: "Live Demo", href: "https://apollosocceracademy.com" },
    deploymentBadge: "Production",
  },
  {
    slug: "apollo-performing-arts-academy",
    title: "Apollo Performing Arts & Academy",
    description:
      "Premier music education platform in Prosper, TX offering professional instruction across various instruments. Built using modern web technologies and AI-assisted design.",
    categories: ["business"],
    badges: [
      { label: "Business", variant: "business" },
      { label: "Education", variant: "info" },
    ],
    techTags: ["HTML5", "Tailwind CSS", "JavaScript", "AOS Animation"],
    features: [
      "SEO Optimization",
      "Responsive UI",
      "Interactive Gallery",
      "Calendly Integration",
      "Schema.org Structured Data",
      "Embedded Video Showcase",
    ],
    link: { label: "Live Demo", href: "https://apolloperformingarts.com" },
    deploymentBadge: "Production",
  },
  {
    slug: "apollo-technologies",
    title: "Apollo Technologies",
    description:
      "Business technology solutions website with service showcase and client portal. Demonstrates AI-assisted development for corporate solutions.",
    categories: ["business"],
    badges: [
      { label: "Business", variant: "business" },
      { label: "Tech Solutions", variant: "info" },
    ],
    techTags: ["Business", "Services", "Corporate", "Solutions"],
    features: [
      "Corporate Identity",
      "Service Showcase",
      "Secure Client Portal",
      "Lead Gen Forms",
      "SEO Optimization",
      "Analytics Dashboard",
    ],
    link: { label: "Live Demo", href: "https://apollotechnologiesus.com" },
    deploymentBadge: "Production",
  },
  {
    slug: "onlinemybiz",
    title: "OnlineMyBiz",
    description:
      "Comprehensive business management portal with tools for small to medium enterprises. Built with AI-generated code for multiple service offerings.",
    categories: ["business"],
    badges: [
      { label: "Business", variant: "business" },
      { label: "Business Portal", variant: "info" },
    ],
    techTags: ["Portal", "Business Tools", "Management", ".net Domain"],
    features: [
      "CRM Integration",
      "Invoice Generation",
      "Client Portal",
      "Task Management",
      "Financial Reporting",
      "Multi-User Access",
    ],
    link: { label: "Live Demo", href: "https://onlinemybiz.net" },
    deploymentBadge: "Production",
  },
  {
    slug: "apollo-stem-academy",
    title: "Apollo STEM Academy",
    description:
      "Educational platform for STEM learning with interactive lessons and progress tracking. Features AI-generated educational tools and learning management.",
    categories: ["education"],
    badges: [
      { label: "Education", variant: "education" },
      { label: "STEM", variant: "education" },
    ],
    techTags: ["Education", "STEM", "Learning", "GitHub Pages"],
    features: [
      "Interactive Labs",
      "Progress Tracking",
      "Gamified Learning",
      "Student Assessments",
      "Resource Library",
      "Teacher Dashboard",
    ],
    link: { label: "Live Demo", href: "https://apollo-stem-academy-api.vercel.app/" },
    deploymentBadge: "GitHub Pages",
  },
  {
    slug: "qrstream-cinematic-qr-generator",
    title: "QrStream – Cinematic QR Generator",
    description:
      "A high-performance QR generation engine featuring a cinematic dark-mode UI. Developed using agentic coding to bridge structural precision with visual excellence. Integrated with the Buildfolio and Apollo 18 ecosystem, featuring advanced Prompt Engineering for dynamic QR attributes and ShortURL capabilities.",
    categories: ["web-app", "ai-powered", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "QrStream", variant: "web-app" },
      { label: "Cinematic UI", variant: "ai" },
      { label: "Vercel", variant: "business" },
    ],
    featured: true,
    techTags: ["Python (Flask)", "Pillow (PIL)", "Tailwind CSS", "Vercel", "HTML5/JS", "LLM-Assisted"],
    features: [
      "Dynamic QR Identity",
      "Real-time Color Custom",
      "Glassmorphism UI",
      "Prompt-Driven Elements",
      "Apollo AI Integration",
      "Mobile-Optimized",
    ],
    link: { label: "Live Application", href: "https://cinematic-qr.vercel.app" },
    deploymentBadge: "v1.2.0",
    impactRating: { stars: 5, label: "Visual Grade" },
  },
  {
    slug: "elite-embroidery-digitization",
    title: "Elite Embroidery Digitization",
    description:
      "A specialized digital showcase platform for high-end embroidery designs. Optimized for speed and visual fidelity, serving as the client-facing portfolio for the Apollo embroidery ecosystem.",
    categories: ["web-app", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Elite Design", variant: "web-app" },
      { label: "Digital Art", variant: "ai" },
    ],
    featured: true,
    techTags: ["Vercel Static", "High Performance", "UX/UI Design"],
    aiTools: ["Midjourney", "Gemini Vision"],
    features: [
      "High-Fidelity Gallery",
      "Vercel Edge Performance",
      "AI-Enhanced Asset Scaling",
      "Precision UX Research",
      "Rapid Mobile Loading",
      "Seamless Client Handoff",
    ],
    link: { label: "Live Application", href: "https://elite-embroidery-digitization.vercel.app/" },
    deploymentBadge: "Vercel Edge",
  },
  {
    slug: "embroidit",
    title: "EmbroidIt",
    description:
      "Custom embroidery e-commerce website built using IONOS website builder platform. Features design customization tools, order management, and online payment processing for embroidery services.",
    categories: [],
    badges: [{ label: "E-commerce", variant: "business" }],
    techTags: ["E-commerce", "Design Tool", "Payment API", ".us Domain"],
    features: [
      "Custom Design Canvas",
      "Secure Stripe Pay",
      "Order History Tracking",
      "User Account System",
      "Inventory Logic",
      "Auto-Email Confirm",
    ],
    link: { label: "Live Demo", href: "https://embroidit.us" },
    deploymentBadge: "Production",
  },
  {
    slug: "embroideryshop-elite-digitizing-service",
    title: "EmbroideryShop Elite – Digitizing Service",
    description:
      "A premium embroidery digitizing platform featuring a cinematic gold-themed UI. Built with agentic precision to provide an elite ordering experience. Integrated with Stripe for secure payments and automated SMTP services for instant file delivery to the embroidery production team.",
    categories: ["web-app", "business", "ai-powered", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "EmbroideryShop", variant: "web-app" },
      { label: "Cinematic UI", variant: "ai" },
      { label: "Vercel", variant: "business" },
    ],
    featured: true,
    techTags: ["Python (Flask)", "Stripe API", "SQLAlchemy", "Tailwind CSS", "Vercel", "LLM-Assisted"],
    features: [
      "Secure Stripe Checkout",
      "Automated Logo Delivery",
      "Persistent Order History",
      "Cinematic Gold Theme UI",
      "Real-time Validation",
      "Dynamic Pricing Engine",
    ],
    link: { label: "Live Application", href: "https://embroidery-shop-green.vercel.app" },
    deploymentBadge: "v1.0.0",
    impactRating: { stars: 5, label: "Visual Grade" },
  },
  {
    slug: "the-neural-dispatch-ai-automated-tech-publication",
    title: "The Neural Dispatch: AI-Automated Tech Publication",
    description:
      "A production-grade static publication for Apollo Technologies US covering AI tools and breakthroughs, powered by two autonomous AI writing agents. PicoClaw generates fast cloud drafts via Google Gemini or Groq, while OpenClaw runs entirely on local Ollama for zero-cost, fully private generation. Each agent writes structured MDX, commits to GitHub, and triggers an automatic Vercel deploy — a hands-off content pipeline from prompt to published article.",
    categories: ["ai-powered", "web-app", "featured", "business"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "AI Agents", variant: "ai" },
      { label: "Content Platform", variant: "web-app" },
      { label: "Next.js 16", variant: "business" },
    ],
    featured: true,
    techTags: ["Next.js 16", "TypeScript", "Tailwind CSS", "MDX", "Framer Motion", "Resend", "Shiki", "next-themes", "Vercel"],
    aiTools: ["Google Gemini", "Groq (Llama 3.3)", "Local Ollama", "Anthropic Claude"],
    features: [
      "Dual AI Writing Agents",
      "MDX Content Pipeline",
      "Auto-Deploy on Push",
      "Dark / Light Theming",
      "Resend Newsletter",
      "SEO Sitemap & OG Images",
    ],
    link: { label: "Live Production", href: "https://www.apollotechnologiesus.com/neural-dispatch" },
    deploymentBadge: "Vercel | Auto-Deploy",
    impactRating: { stars: 5, label: "Content Automation" },
  },
  {
    slug: "certideed-blockchain-document-registry-for-title-closings",
    title: "CertiDeed: Blockchain Document Registry for Title Closings",
    description:
      "A blockchain-based document registry that gives real estate title companies tamper-proof, independently verifiable records for every closing. Documents are hashed and anchored on-chain through a Solidity smart contract, so any party — lender, attorney, or court — can verify authenticity in seconds. A Node.js / Express API bridges the chain to a PostgreSQL system of record, enforces JWT role-based access, and generates complete audit-trail PDFs for every transaction.",
    categories: ["web3", "business", "web-app", "featured"],
    badges: [
      { label: "Featured", variant: "featured" },
      { label: "Blockchain", variant: "ai" },
      { label: "LegalTech", variant: "business" },
      { label: "Web App", variant: "web-app" },
    ],
    featured: true,
    techTags: ["Solidity", "Hardhat", "OpenZeppelin", "ethers.js", "Node.js", "Express", "PostgreSQL", "Next.js 16", "JWT", "PDFKit"],
    aiTools: ["Claude Sonnet", "Agentic Workflows"],
    features: [
      "On-Chain Hash Anchoring",
      "Tamper-Proof Verification",
      "Smart-Contract Registry",
      "JWT Role-Based Access",
      "Audit-Trail PDF Export",
      "Polygon Deployment",
    ],
    link: { label: "Live Production", href: "https://www.certideed.com/" },
    deploymentBadge: "Polygon + Local Node",
    impactRating: { stars: 5, label: "LegalTech Integrity" },
  },
  {
    slug: "whatsapp-link-extractor-knowledge-base-builder",
    title: "WhatsApp Link Extractor & Knowledge Base Builder",
    description:
      "A Python toolkit that turns years of shared WhatsApp group links into a searchable knowledge base. It parses chat exports to extract and categorize links by topic (AI, tech, career, science, finance), then crawls each URL to build a structured archive — full-text articles, AI-generated summaries, a CSV / JSON dataset, and a visual word-cloud report. Resilient by design, it saves progress and resumes safely across hundreds of links.",
    categories: ["ai-powered", "productivity"],
    badges: [
      { label: "AI-Powered", variant: "ai" },
      { label: "Data Tool", variant: "productivity" },
      { label: "Python CLI", variant: "web-app" },
    ],
    techTags: ["Python", "newspaper4k", "trafilatura", "BeautifulSoup", "NLTK", "pdfplumber"],
    aiTools: ["OpenAI GPT", "WordCloud"],
    features: [
      "Topic-Aware Link Extraction",
      "Multi-Engine Content Scraper",
      "AI Article Summaries",
      "Resumable Batch Processing",
      "CSV / JSON Export",
      "Word-Cloud Reporting",
    ],
    link: { label: "Local CLI Tool", href: "#" },
    deploymentBadge: "Local Python CLI",
    impactRating: { stars: 4, label: "Research Utility" },
  },
];

export const filterOptions: { label: string; value: "all" | ProjectCategory }[] = [
  { label: "All Projects", value: "all" },
  { label: "Featured & SaaS", value: "featured" },
  { label: "AI-Powered", value: "ai-powered" },
  { label: "Web3 & Blockchain", value: "web3" },
  { label: "Business Solutions", value: "business" },
  { label: "Productivity", value: "productivity" },
  { label: "Education", value: "education" },
];
